# Generated by Django 4.1.7 on 2023-02-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id_associer', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'associer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateCreate',
            fields=[
                ('jour', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'date_create',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('libele', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mod_file', models.CharField(max_length=255)),
                ('accuracy', models.DecimalField(decimal_places=4, max_digits=15)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id_predict', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('bonne_pred', models.BooleanField()),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'predict',
                'managed': False,
            },
        ),
    ]
